### ISSUE TITLE
dataValues is sometimes equal to .end()

### ISSUE THREAD

**Issue by cwpearson** [cwpearson/cupti#24]
https://github.com/cwpearson/cupti/blob/42373bbf079d7d4c97da33ed27cfa33e2ab2308d/profiler/src/kernel_time.cpp#L336

**Comment by dominicgrande** [comment]
I added some temporary sanity checks. However, this should never happen. I will go through and try to fix what is causing that so there aren't more issues down the line.

**Comment by cwpearson** [comment]
It was happening to me when I ran a multi-gpu training in caffe-1.0

**Comment by cwpearson** [comment]
This also happens when I run examples/samples/matrixMul/mm which might make it easier to debug

**Comment by dominicgrande** [comment]
The code in https://github.com/cwpearson/cupti/commit/2ab3c5202a7583c27c689ae7e655d0091ecd5217 should have gotten rid of this issue for the Activity callbacks.
