### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by vastskymiaow** [cwpearson/cupti#53]
Hi, when I compile  and install the application in the step `make`.
It occurs the error with the ERROR followed by:
callbacks.cpp: In function 'void handleCudaConfigureCall(const CUpti_CallbackData*)':
callbacks.cpp:580:21: error: 'cudaConfigureCall_v3020_params' was not declared in this scope
     auto params = ((cudaConfigureCall_v3020_params *)(cbInfo->functionParams));
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
callbacks.cpp:580:21: note: suggested alternative: 'cudaEventCreate_v3020_params'
     auto params = ((cudaConfigureCall_v3020_params *)(cbInfo->functionParams));
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                     cudaEventCreate_v3020_params
callbacks.cpp:580:53: error: expected primary-expression before ')' token
     auto params = ((cudaConfigureCall_v3020_params *)(cbInfo->functionParams));
                                                     ^
callbacks.cpp: In function 'void handleCudaSetupArgument(const CUpti_CallbackData*)':
callbacks.cpp:596:11: error: 'cudaSetupArgument_v3020_params' was not declared in this scope
         ((cudaSetupArgument_v3020_params *)(cbInfo->functionParams));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
callbacks.cpp:596:11: note: suggested alternative: 'cudaStreamQuery_v3020_params'
         ((cudaSetupArgument_v3020_params *)(cbInfo->functionParams));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           cudaStreamQuery_v3020_params
callbacks.cpp:596:43: error: expected primary-expression before ')' token
         ((cudaSetupArgument_v3020_params *)(cbInfo->functionParams));
                                           ^
callbacks.cpp: In function 'void handleCudaStreamCreate(const CUpti_CallbackData*)':
callbacks.cpp:617:24: warning: unused variable 'stream' [-Wunused-variable]
     const cudaStream_t stream = *(params->pStream);
                        ^~~~~~
callbacks.cpp: In function 'void handleCudaStreamDestroy(const CUpti_CallbackData*)':
callbacks.cpp:628:11: error: 'cudaStreamDestroy_v3020_params' was not declared in this scope
         ((cudaStreamDestroy_v3020_params *)(cbInfo->functionParams));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
callbacks.cpp:628:11: note: suggested alternative: 'cudaStreamDestroy_v5050_params'
         ((cudaStreamDestroy_v3020_params *)(cbInfo->functionParams));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           cudaStreamDestroy_v5050_params
callbacks.cpp:628:43: error: expected primary-expression before ')' token
         ((cudaStreamDestroy_v3020_params *)(cbInfo->functionParams));
                                           ^
callbacks.cpp:629:24: warning: unused variable 'stream' [-Wunused-variable]
     const cudaStream_t stream = params->stream;
                        ^~~~~~
callbacks.cpp: In function 'void handleCudaStreamSynchronize(const CUpti_CallbackData*)':
callbacks.cpp:641:24: warning: unused variable 'stream' [-Wunused-variable]
     const cudaStream_t stream = params->stream;
                        ^~~~~~
Makefile:43: recipe for target 'callbacks.o' failed
make: *** [callbacks.o] Error 1

-------------------------------------------------
Can you help me to find the resolution to success making it.

**Comment by cwpearson** [comment]
Hi,

I haven't developed this for a while - it looks like the CUDA library you're using is too new (e.g., the `cudaStreamDestroy_v3020_params` struct has been replaced with a `cudaStreamDestroy_v5050_params` struct.

If you're interested in using CuPTI, the general structure of this code is probably still correct, but the various functions will have different parameters today.

I'm not currently planning on updating or maintaining this code. Sorry for the inconvenience.
